from datetime import datetime
from couchdb.mapping import Document,IntegerField, TextField, BooleanField, ListField, DictField, DateTimeField, TimeField
# Create your models here.

class Per_Conf(Document):
    id = TextField()
    build_id = TextField()
    count = IntegerField()
    hash_key = TextField()
    os_label = TextField()
    test_runner = TextField()
    handlers = ListField(TextField(),name='handler')
    schedule_time = DateTimeField()
    shedule = ListField(TextField(),name='day')
    to_run = BooleanField()
    slot = TextField()
    filename = TextField()
    project = TextField()
    platform = TextField()
    test_group = ListField(TextField(),name='group')
    schedule_type = TextField()
    test_env = TextField()
    type = TextField()

class Per_Test(Document):
    status = TextField()
    slot = TextField()
    test_runner = TextField()
    test_group = TextField()
    trigger_on = DateTimeField()
    build_id = TextField()
    hash_key = TextField()
    os_label = TextField()
    handlers = ListField(TextField(),name ='handler')
    finish_time = DateTimeField()
    count = IntegerField()
    filename = TextField()
    project = TextField()
    platform = TextField()
    test_env = TextField()
    type = TextField()
    start_time = DateTimeField()

class First_Test(Document):
    status = TextField()
    slot = TextField()
    test_runner = TextField()
    test_group = TextField()
    trigger_on = DateTimeField()
    build_id = TextField()
    hash_key = TextField()
    os_label = TextField()
    handlers = ListField(TextField(),name ='handler')
    finish_time = DateTimeField()
    count = IntegerField()
    filename = TextField()
    project = TextField()
    platform = TextField()
    test_env = TextField()
    type = TextField()
    start_time = DateTimeField()

class Test_Run(Document):
    status = TextField()
    slot = TextField()
    test_runner = TextField()
    test_group = TextField()
    trigger_on = DateTimeField()
    build_id = TextField()
    hash_key = TextField()
    os_label = TextField()
    handlers = ListField(TextField(),name ='handler')
    finish_time = DateTimeField()
    count = IntegerField()
    filename = TextField()
    project = TextField()
    platform = TextField()
    test_env = TextField()
    type = TextField()
    start_time = DateTimeField()


